# Generated by Django 5.2.5 on 2025-11-20 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminprofile',
            options={'ordering': ('-created_at',), 'verbose_name': 'Admin Profile', 'verbose_name_plural': 'Admin Profiles'},
        ),
        migrations.AlterModelOptions(
            name='clerkprofile',
            options={'ordering': ('-created_at',), 'verbose_name': 'Clerk Profile', 'verbose_name_plural': 'Clerk Profiles'},
        ),
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='extendedpermission',
            options={'ordering': ('-created_at',), 'verbose_name': 'Extended Permission', 'verbose_name_plural': 'Extended Permissions'},
        ),
        migrations.AlterModelOptions(
            name='guardianprofile',
            options={'ordering': ('-created_at',), 'verbose_name': 'Guardian Profile', 'verbose_name_plural': 'Guardian Profiles'},
        ),
        migrations.AlterModelOptions(
            name='permission',
            options={'ordering': ('name', '-created_at'), 'verbose_name': 'Permission', 'verbose_name_plural': 'Permissions'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ('name', '-created_at'), 'verbose_name': 'Role', 'verbose_name_plural': 'Roles'},
        ),
        migrations.AlterModelOptions(
            name='rolepermission',
            options={'ordering': ('-created_at',), 'verbose_name': 'Role Permission', 'verbose_name_plural': 'Role Permissions'},
        ),
        migrations.AlterModelOptions(
            name='studentguardian',
            options={'ordering': ('-created_at',), 'verbose_name': 'Student guardian', 'verbose_name_plural': 'Student guardians'},
        ),
        migrations.AlterModelOptions(
            name='studentprofile',
            options={'ordering': ('-created_at',), 'verbose_name': 'Student Profile', 'verbose_name_plural': 'Student Profiles'},
        ),
        migrations.AlterModelOptions(
            name='teacherprofile',
            options={'ordering': ('-created_at',), 'verbose_name': 'Teacher Profile', 'verbose_name_plural': 'Teacher Profiles'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('-created_at',), 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.RenameField(
            model_name='adminprofile',
            old_name='date_created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='adminprofile',
            old_name='date_modified',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='clerkprofile',
            old_name='date_created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='clerkprofile',
            old_name='date_modified',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='device',
            old_name='date_created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='device',
            old_name='date_modified',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='extendedpermission',
            old_name='date_created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='extendedpermission',
            old_name='date_modified',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='guardianprofile',
            old_name='date_created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='guardianprofile',
            old_name='date_modified',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='permission',
            old_name='date_created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='permission',
            old_name='date_modified',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='date_created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='date_modified',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='rolepermission',
            old_name='date_created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='rolepermission',
            old_name='date_modified',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='studentguardian',
            old_name='date_created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='studentguardian',
            old_name='date_modified',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='studentprofile',
            old_name='date_created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='studentprofile',
            old_name='date_modified',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='teacherprofile',
            old_name='date_created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='teacherprofile',
            old_name='date_modified',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='date_created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='date_modified',
            new_name='updated_at',
        ),
    ]
