# Generated by Django 5.2.5 on 2025-12-06 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_adminprofile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='force_pass_reset',
            field=models.BooleanField(default=False, help_text='User must update password on next login.'),
        ),
    ]
