# Generated by Django 5.2.5 on 2025-09-20 09:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_device'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='guardians',
        ),
        migrations.AddField(
            model_name='studentguardian',
            name='can_receive_reports',
            field=models.BooleanField(default=True, help_text='Authorized to receive student notifications and communications.', verbose_name='Can receive reports'),
        ),
        migrations.AddField(
            model_name='studentguardian',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is active'),
        ),
        migrations.AlterField(
            model_name='device',
            name='token',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='studentguardian',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_guardians', to=settings.AUTH_USER_MODEL, verbose_name='Student'),
        ),
    ]
