# Generated by Django 5.2.5 on 2025-12-11 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('GUARDIAN', 'Guardian'), ('TEACHER', 'Teacher'), ('CLERK', 'Clerk'), ('ADMIN', 'Admin')], max_length=50, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='studentguardian',
            name='relationship',
            field=models.CharField(blank=True, choices=[('FATHER', 'Father'), ('MOTHER', 'Mother'), ('GUARDIAN', 'Guardian'), ('UNCLE', 'Uncle'), ('AUNT', 'Aunt'), ('BROTHER', 'Brother'), ('SISTER', 'Sister'), ('GRANDFATHER', 'Grandfather'), ('GRANDMOTHER', 'Grandmother'), ('OTHER', 'Other')], default='OTHER', help_text="The guardian's relationship to the student.", max_length=20, verbose_name='Relationship'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], default='OTHER', max_length=10),
        ),
    ]
