# Generated by Django 5.2.5 on 2025-09-20 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_studentprofile_guardians_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('student', 'Student'), ('guardian', 'Guardian'), ('teacher', 'Teacher'), ('clerk', 'Clerk'), ('admin', 'Admin')], max_length=50, unique=True, verbose_name='Name'),
        ),
    ]
