# Generated by Django 5.2.5 on 2025-12-13 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_classroom_grade_level'),
        ('users', '0005_alter_role_name_alter_studentguardian_relationship_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='branch',
        ),
        migrations.AddField(
            model_name='user',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='schools.school', verbose_name='School'),
        ),
    ]
