# Generated by Django 5.2.5 on 2025-12-13 14:16

import audit.mixins
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_classroom_grade_level'),
        ('users', '0006_remove_user_branch_user_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clerkprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='guardianprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='classroom',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='additional_info',
            field=models.TextField(blank=True, null=True, verbose_name='Additional information'),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email address'),
        ),
        migrations.AddField(
            model_name='user',
            name='id_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='ID number'),
        ),
        migrations.AddField(
            model_name='user',
            name='knec_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='KNEC number'),
        ),
        migrations.AddField(
            model_name='user',
            name='medical_info',
            field=models.TextField(blank=True, null=True, verbose_name='Medical information'),
        ),
        migrations.AddField(
            model_name='user',
            name='nemis_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='NEMIS number'),
        ),
        migrations.AddField(
            model_name='user',
            name='occupation',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Occupation'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Phone number'),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('GRADUATED', 'Graduated'), ('TRANSFERRED', 'Transferred'), ('TERMINATED', 'Terminated'), ('ON_LEAVE', 'On Leave')], default='ACTIVE', max_length=20, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='user',
            name='tsc_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='TSC number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='force_pass_reset',
            field=models.BooleanField(default=False, help_text='User must update password on next login.', verbose_name='Force password reset'),
        ),
        migrations.AlterField(
            model_name='user',
            name='reg_number',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Registration number'),
        ),
        migrations.CreateModel(
            name='StudentClassroomAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Unique identifier')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date modified')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('synced', models.BooleanField(default=False, help_text='Indicates whether this record has been synchronized with the replica system.', verbose_name='Synced')),
                ('academic_year', models.CharField(max_length=20, verbose_name='Academic year')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PROMOTED', 'Promoted'), ('TRANSFERRED', 'Transferred'), ('REPEATED', 'Repeated')], default='ACTIVE', max_length=20, verbose_name='Status')),
                ('is_current', models.BooleanField(default=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classroom_students', to='schools.classroom', verbose_name='Classroom')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_classrooms', to=settings.AUTH_USER_MODEL, verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Student Classroom',
                'verbose_name_plural': 'Student Classrooms',
                'ordering': ('-created_at',),
            },
            bases=(audit.mixins.AuditableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='StudentClassroomMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Unique identifier')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date modified')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('synced', models.BooleanField(default=False, help_text='Indicates whether this record has been synchronized with the replica system.', verbose_name='Synced')),
                ('academic_year', models.CharField(max_length=20, verbose_name='Academic year')),
                ('movement_type', models.CharField(choices=[('ADMISSION', 'Admission'), ('PROMOTION', 'Promotion'), ('STREAM_CHANGE', 'Stream Change'), ('REPEAT', 'Repeat'), ('TRANSFER_OUT', 'Transfer Out'), ('GRADUATION', 'Graduation'), ('WITHDRAWAL', 'Withdrawal')], max_length=30, verbose_name='Movement Type')),
                ('reason', models.TextField(blank=True, verbose_name='Reason')),
                ('from_classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='schools.classroom', verbose_name='From Classroom')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_movements', to=settings.AUTH_USER_MODEL, verbose_name='Performed By')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classroom_movements', to=settings.AUTH_USER_MODEL, verbose_name='Student')),
                ('to_classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='schools.classroom', verbose_name='To Classroom')),
            ],
            bases=(audit.mixins.AuditableMixin, models.Model),
        ),
        migrations.DeleteModel(
            name='AdminProfile',
        ),
        migrations.DeleteModel(
            name='ClerkProfile',
        ),
        migrations.DeleteModel(
            name='GuardianProfile',
        ),
        migrations.DeleteModel(
            name='StudentProfile',
        ),
        migrations.DeleteModel(
            name='TeacherProfile',
        ),
        migrations.AddConstraint(
            model_name='studentclassroomassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('student', 'academic_year'), name='one_active_class_per_year'),
        ),
        migrations.AddIndex(
            model_name='studentclassroommovement',
            index=models.Index(fields=['student'], name='users_stude_student_083514_idx'),
        ),
        migrations.AddIndex(
            model_name='studentclassroommovement',
            index=models.Index(fields=['academic_year'], name='users_stude_academi_7b9190_idx'),
        ),
        migrations.AddIndex(
            model_name='studentclassroommovement',
            index=models.Index(fields=['movement_type'], name='users_stude_movemen_2b865e_idx'),
        ),
    ]
