# Generated by Django 5.2.5 on 2025-12-13 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_clerkprofile_user_remove_guardianprofile_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='user',
            name='county_of_residence',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='County of residence'),
        ),
        migrations.AddField(
            model_name='user',
            name='town_of_residence',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Town of residence'),
        ),
    ]
