# Generated by Django 5.2.5 on 2025-12-13 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_address_user_county_of_residence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='student_type',
            field=models.CharField(blank=True, choices=[('DAY_SCHOLAR', 'Day Scholar'), ('BOARDER', 'Boarder')], help_text='Indicates whether the student is a day scholar or boarder.', max_length=20, null=True, verbose_name='Student Type'),
        ),
        migrations.AddField(
            model_name='user',
            name='subscribed_to_meals',
            field=models.BooleanField(default=False, help_text='Whether the student is enrolled in the school feeding program.', verbose_name='Subscribed to school meals'),
        ),
        migrations.AddField(
            model_name='user',
            name='subscribed_to_transport',
            field=models.BooleanField(default=False, help_text='Whether the student uses school-provided transport.', verbose_name='Subscribed to school transport'),
        ),
    ]
