# Generated by Django 5.2.5 on 2025-12-13 18:49

import audit.mixins
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_student_type_user_subscribed_to_meals_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='additional_info',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='id_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='knec_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='medical_info',
        ),
        migrations.RemoveField(
            model_name='user',
            name='nemis_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='occupation',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='status',
        ),
        migrations.RemoveField(
            model_name='user',
            name='student_type',
        ),
        migrations.RemoveField(
            model_name='user',
            name='subscribed_to_meals',
        ),
        migrations.RemoveField(
            model_name='user',
            name='subscribed_to_transport',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tsc_number',
        ),
        migrations.AlterField(
            model_name='user',
            name='force_pass_reset',
            field=models.BooleanField(default=False, help_text='User must update password on next login.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='reg_number',
            field=models.CharField(blank=True, help_text='Unique school registration number assigned to this user.', max_length=50, unique=True, verbose_name='Registration number'),
        ),
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Unique identifier')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date modified')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('synced', models.BooleanField(default=False, help_text='Indicates whether this record has been synchronized with the replica system.', verbose_name='Synced')),
                ('id_number', models.CharField(blank=True, max_length=20, unique=True, verbose_name='ID number')),
                ('phone_number', models.CharField(blank=True, max_length=12, unique=True, verbose_name='Phone number')),
                ('email', models.EmailField(blank=True, max_length=254, unique=True, verbose_name='Email address')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('TERMINATED', 'Terminated'), ('ON_LEAVE', 'On Leave')], default='ACTIVE', max_length=20, verbose_name='Status')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Admin Profile',
                'verbose_name_plural': 'Admin Profiles',
                'ordering': ('-created_at',),
            },
            bases=(audit.mixins.AuditableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ClerkProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Unique identifier')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date modified')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('synced', models.BooleanField(default=False, help_text='Indicates whether this record has been synchronized with the replica system.', verbose_name='Synced')),
                ('id_number', models.CharField(max_length=20, unique=True, verbose_name='ID number')),
                ('phone_number', models.CharField(blank=True, max_length=12, unique=True, verbose_name='Phone number')),
                ('email', models.EmailField(blank=True, max_length=254, unique=True, verbose_name='Email address')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('TERMINATED', 'Terminated'), ('ON_LEAVE', 'On Leave')], default='ACTIVE', max_length=20, verbose_name='Status')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clerk_profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Clerk Profile',
                'verbose_name_plural': 'Clerk Profiles',
                'ordering': ('-created_at',),
            },
            bases=(audit.mixins.AuditableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='GuardianProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Unique identifier')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date modified')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('synced', models.BooleanField(default=False, help_text='Indicates whether this record has been synchronized with the replica system.', verbose_name='Synced')),
                ('id_number', models.CharField(max_length=20, unique=True, verbose_name='ID number')),
                ('phone_number', models.CharField(max_length=20, unique=True, verbose_name='Phone number')),
                ('email', models.EmailField(blank=True, max_length=254, unique=True, verbose_name='Email address')),
                ('occupation', models.CharField(blank=True, max_length=100, verbose_name='Occupation')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active')], default='ACTIVE', max_length=20, verbose_name='Status')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guardian_profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Guardian Profile',
                'verbose_name_plural': 'Guardian Profiles',
                'ordering': ('-created_at',),
            },
            bases=(audit.mixins.AuditableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Unique identifier')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date modified')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('synced', models.BooleanField(default=False, help_text='Indicates whether this record has been synchronized with the replica system.', verbose_name='Synced')),
                ('student_type', models.CharField(blank=True, choices=[('DAY_SCHOLAR', 'Day Scholar'), ('BOARDER', 'Boarder')], help_text='Indicates whether the student is a day scholar or a boarder.', max_length=20, null=True, verbose_name='Student Type')),
                ('knec_number', models.CharField(blank=True, max_length=50, unique=True, verbose_name='KNEC number')),
                ('nemis_number', models.CharField(blank=True, max_length=50, unique=True, verbose_name='NEMIS number')),
                ('subscribed_to_transport', models.BooleanField(default=False, help_text='Whether the student uses school-provided transport.', verbose_name='Subscribed to school transport')),
                ('subscribed_to_meals', models.BooleanField(default=False, help_text='Whether the student is enrolled in the school feeding program.', verbose_name='Subscribed to school meals')),
                ('medical_info', models.TextField(blank=True, null=True, verbose_name='Medical information')),
                ('additional_info', models.TextField(blank=True, null=True, verbose_name='Additional information')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('GRADUATED', 'Graduated'), ('TRANSFERRED', 'Transferred')], default='ACTIVE', max_length=20, verbose_name='Status')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Student Profile',
                'verbose_name_plural': 'Student Profiles',
                'ordering': ('-created_at',),
            },
            bases=(audit.mixins.AuditableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Unique identifier')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date modified')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('synced', models.BooleanField(default=False, help_text='Indicates whether this record has been synchronized with the replica system.', verbose_name='Synced')),
                ('tsc_number', models.CharField(max_length=50, unique=True, verbose_name='TSC number')),
                ('id_number', models.CharField(max_length=20, unique=True, verbose_name='ID number')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone number')),
                ('email', models.EmailField(blank=True, max_length=254, unique=True, verbose_name='Email address')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('RETIRED', 'Retired'), ('TERMINATED', 'Terminated'), ('ON_LEAVE', 'On Leave')], default='ACTIVE', max_length=20, verbose_name='Status')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Teacher Profile',
                'verbose_name_plural': 'Teacher Profiles',
                'ordering': ('-created_at',),
            },
            bases=(audit.mixins.AuditableMixin, models.Model),
        ),
    ]
