# Generated by Django 5.2.5 on 2025-12-13 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_user_additional_info_remove_user_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='force_pass_reset',
            field=models.BooleanField(default=False, help_text='User must update password on next login.', verbose_name='Force password reset'),
        ),
    ]
