# Generated by Django 5.2.5 on 2025-12-15 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_user_force_pass_reset'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='admission_date',
            field=models.DateField(blank=True, null=True, verbose_name='Admission date'),
        ),
    ]
