# Generated by Django 5.2.5 on 2025-12-15 16:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_studentprofile_admission_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email address'),
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='id_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='ID number'),
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12, verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='clerkprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email address'),
        ),
        migrations.AlterField(
            model_name='clerkprofile',
            name='id_number',
            field=models.CharField(max_length=20, verbose_name='ID number'),
        ),
        migrations.AlterField(
            model_name='clerkprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12, verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='device',
            name='last_activity',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 12, 15, 16, 3, 14, 382767, tzinfo=datetime.timezone.utc), editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='guardianprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email address'),
        ),
        migrations.AlterField(
            model_name='guardianprofile',
            name='id_number',
            field=models.CharField(max_length=20, verbose_name='ID number'),
        ),
        migrations.AlterField(
            model_name='guardianprofile',
            name='phone_number',
            field=models.CharField(max_length=20, verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email address'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='id_number',
            field=models.CharField(max_length=20, verbose_name='ID number'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Phone number'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='tsc_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='TSC number'),
        ),
    ]
