# Generated by Django 5.2.5 on 2025-12-15 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_classroom_grade_level'),
        ('users', '0013_alter_adminprofile_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='branches',
            field=models.ManyToManyField(blank=True, help_text='Branches this user is assigned to. Leave blank for access to ALL branches in the school.', related_name='assigned_users', to='schools.branch', verbose_name='Assigned Branches'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='knec_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='KNEC number'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='nemis_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='NEMIS number'),
        ),
    ]
