# Generated by Django 5.2.5 on 2025-12-15 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_user_branches_alter_studentprofile_knec_number_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='studentclassroomassignment',
            name='one_active_class_per_year',
        ),
        migrations.AlterUniqueTogether(
            name='studentclassroomassignment',
            unique_together={('student', 'is_current')},
        ),
        migrations.AlterField(
            model_name='studentclassroommovement',
            name='movement_type',
            field=models.CharField(choices=[('ADMISSION', 'Admission'), ('PROMOTION', 'Promotion'), ('STREAM_CHANGE', 'Stream change'), ('REPEAT', 'Repeat'), ('TRANSFER_OUT', 'Transfer out'), ('GRADUATION', 'Graduation'), ('WITHDRAWAL', 'Withdrawal')], max_length=30, verbose_name='Movement Type'),
        ),
        migrations.RemoveField(
            model_name='studentclassroomassignment',
            name='status',
        ),
    ]
