# Generated by Django 5.2.5 on 2025-12-24 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_remove_studentclassroomassignment_one_active_class_per_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
