# Generated by Django 5.2.5 on 2025-12-25 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='clerkprofile',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='guardianprofile',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
    ]
