# Generated by Django 5.2.5 on 2026-01-04 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_adminprofile_is_active_clerkprofile_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='other_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Other name'),
        ),
    ]
