# Generated by Django 5.2.5 on 2025-11-20 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apiclientkey',
            options={'ordering': ['-created_at'], 'verbose_name': 'API Client Key', 'verbose_name_plural': 'API Client Keys'},
        ),
        migrations.AlterModelOptions(
            name='ratelimitblock',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='systemkey',
            options={'ordering': ['-created_at'], 'verbose_name': 'System Key', 'verbose_name_plural': 'System Keys'},
        ),
        migrations.RenameField(
            model_name='apicallback',
            old_name='date_created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='apicallback',
            old_name='date_modified',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='apiclient',
            old_name='date_created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='apiclient',
            old_name='date_modified',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='apiclientkey',
            old_name='date_created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='apiclientkey',
            old_name='date_modified',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='ratelimitattempt',
            old_name='date_created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='ratelimitattempt',
            old_name='date_modified',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='ratelimitblock',
            old_name='date_created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='ratelimitblock',
            old_name='date_modified',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='ratelimitrule',
            old_name='date_created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='ratelimitrule',
            old_name='date_modified',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='systemkey',
            old_name='date_created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='systemkey',
            old_name='date_modified',
            new_name='updated_at',
        ),
    ]
