# Generated by Django 5.2.5 on 2025-12-11 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_apiclientkey_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ratelimitattempt',
            options={'ordering': ['-last_attempt'], 'verbose_name': 'Rate Limit Attempt', 'verbose_name_plural': 'Rate Limit Attempts'},
        ),
        migrations.AlterModelOptions(
            name='ratelimitblock',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Rate Limit Block', 'verbose_name_plural': 'Rate Limit Blocks'},
        ),
        migrations.AlterModelOptions(
            name='ratelimitrule',
            options={'ordering': ['name', '-priority'], 'verbose_name': 'Rate Limit Rule', 'verbose_name_plural': 'Rate Limit Rules'},
        ),
        migrations.AlterField(
            model_name='apicallback',
            name='client',
            field=models.ForeignKey(help_text='API client associated with this callback.', on_delete=django.db.models.deletion.CASCADE, related_name='callbacks', to='api.apiclient', verbose_name='API Client'),
        ),
        migrations.AlterField(
            model_name='apicallback',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indicates whether this callback is active.', verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='apicallback',
            name='path',
            field=models.CharField(help_text='URL path pattern or endpoint for the callback.', max_length=255, unique=True, verbose_name='Callback Path'),
        ),
        migrations.AlterField(
            model_name='apicallback',
            name='require_authentication',
            field=models.BooleanField(default=False, help_text='If True, the callback requires API key authentication.', verbose_name='Require Authentication'),
        ),
        migrations.AlterField(
            model_name='apiclient',
            name='allowed_ips',
            field=models.TextField(blank=True, help_text='Comma-separated list of allowed IPs for request validation.', verbose_name='Allowed IPs'),
        ),
        migrations.AlterField(
            model_name='apiclient',
            name='api_key',
            field=models.CharField(editable=False, help_text='Unique API key identifying this client.', max_length=64, unique=True, verbose_name='API Key'),
        ),
        migrations.AlterField(
            model_name='apiclient',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this client is active.', verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='apiclient',
            name='meta',
            field=models.JSONField(blank=True, help_text='Optional metadata about the client (contact info, environment, etc.).', null=True, verbose_name='Metadata'),
        ),
        migrations.AlterField(
            model_name='apiclient',
            name='name',
            field=models.CharField(help_text='Name of the external system or partner.', max_length=100, unique=True, verbose_name='Client Name'),
        ),
        migrations.AlterField(
            model_name='apiclient',
            name='require_signature_verification',
            field=models.BooleanField(default=False, help_text='If True, incoming requests must include a valid cryptographic signature.', verbose_name='Require Signature Verification'),
        ),
        migrations.AlterField(
            model_name='apiclient',
            name='signature_algorithm',
            field=models.CharField(choices=[('HMAC-SHA256', 'HMAC-SHA256'), ('RSA-SHA256', 'RSA-SHA256')], default='HMAC-SHA256', help_text='Algorithm used to verify callback signatures.', max_length=20, verbose_name='Signature Algorithm'),
        ),
        migrations.AlterField(
            model_name='apiclient',
            name='signature_header_key',
            field=models.CharField(default='x-signature', help_text='Header name containing the callback signature.', max_length=50, verbose_name='Signature Header Key'),
        ),
        migrations.AlterField(
            model_name='apiclient',
            name='signature_secret',
            field=models.CharField(blank=True, help_text='Shared secret for HMAC signature validation of callbacks.', max_length=255, null=True, verbose_name='Signature Secret'),
        ),
        migrations.AlterField(
            model_name='apiclientkey',
            name='client',
            field=models.ForeignKey(help_text='Owning API client for this key.', on_delete=django.db.models.deletion.CASCADE, related_name='keys', to='api.apiclient', verbose_name='API Client'),
        ),
        migrations.AlterField(
            model_name='apiclientkey',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expiration Time'),
        ),
        migrations.AlterField(
            model_name='apiclientkey',
            name='fingerprint',
            field=models.CharField(db_index=True, help_text='SHA-256 fingerprint of the public key for quick lookup.', max_length=64, verbose_name='Fingerprint'),
        ),
        migrations.AlterField(
            model_name='apiclientkey',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indicates if this key is currently active.', verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='apiclientkey',
            name='public_key',
            field=models.TextField(help_text="The client's public key in PEM format.", verbose_name='Public Key'),
        ),
        migrations.AlterField(
            model_name='ratelimitattempt',
            name='count',
            field=models.PositiveIntegerField(default=1, verbose_name='Attempt Count'),
        ),
        migrations.AlterField(
            model_name='ratelimitattempt',
            name='endpoint',
            field=models.CharField(blank=True, max_length=200, verbose_name='Endpoint'),
        ),
        migrations.AlterField(
            model_name='ratelimitattempt',
            name='key',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Key'),
        ),
        migrations.AlterField(
            model_name='ratelimitattempt',
            name='last_attempt',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Attempt'),
        ),
        migrations.AlterField(
            model_name='ratelimitattempt',
            name='method',
            field=models.CharField(max_length=10, verbose_name='HTTP Method'),
        ),
        migrations.AlterField(
            model_name='ratelimitattempt',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ratelimitrule', verbose_name='Rule'),
        ),
        migrations.AlterField(
            model_name='ratelimitattempt',
            name='window_start',
            field=models.DateTimeField(db_index=True, verbose_name='Window Start'),
        ),
        migrations.AlterField(
            model_name='ratelimitblock',
            name='blocked_until',
            field=models.DateTimeField(db_index=True, verbose_name='Blocked Until'),
        ),
        migrations.AlterField(
            model_name='ratelimitblock',
            name='key',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Key'),
        ),
        migrations.AlterField(
            model_name='ratelimitblock',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ratelimitrule', verbose_name='Rule'),
        ),
        migrations.AlterField(
            model_name='ratelimitrule',
            name='block_duration_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Block duration after limit exceeded (0 = no blocking)', verbose_name='Block Duration (Minutes)'),
        ),
        migrations.AlterField(
            model_name='ratelimitrule',
            name='endpoint_pattern',
            field=models.CharField(blank=True, help_text='Regex pattern for URL matching', max_length=200, verbose_name='Endpoint Pattern'),
        ),
        migrations.AlterField(
            model_name='ratelimitrule',
            name='http_methods',
            field=models.CharField(blank=True, help_text='Comma-separated HTTP methods (GET,POST,etc)', max_length=50, verbose_name='HTTP Methods'),
        ),
        migrations.AlterField(
            model_name='ratelimitrule',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='ratelimitrule',
            name='limit',
            field=models.PositiveIntegerField(help_text='Number of requests allowed', verbose_name='Limit'),
        ),
        migrations.AlterField(
            model_name='ratelimitrule',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Rule Name'),
        ),
        migrations.AlterField(
            model_name='ratelimitrule',
            name='period',
            field=models.CharField(choices=[('second', 'Second'), ('minute', 'Minute'), ('hour', 'Hour'), ('day', 'Day'), ('week', 'Week'), ('month', 'Month')], max_length=10, verbose_name='Period'),
        ),
        migrations.AlterField(
            model_name='ratelimitrule',
            name='period_count',
            field=models.PositiveIntegerField(default=1, help_text="Number of periods (e.g., 2 for '2 hours')", verbose_name='Period Count'),
        ),
        migrations.AlterField(
            model_name='ratelimitrule',
            name='priority',
            field=models.IntegerField(default=0, help_text='Higher priority rules are checked first', verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='ratelimitrule',
            name='scope',
            field=models.CharField(choices=[('global', 'Global'), ('api_client', 'API Client'), ('user', 'Per User'), ('ip', 'Per IP'), ('endpoint', 'Per Endpoint'), ('api_client_endpoint', 'API Client + Endpoint'), ('user_endpoint', 'Per User + Endpoint'), ('ip_endpoint', 'Per IP + Endpoint')], max_length=20, verbose_name='Scope'),
        ),
        migrations.AlterField(
            model_name='systemkey',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expiration Time'),
        ),
        migrations.AlterField(
            model_name='systemkey',
            name='fingerprint',
            field=models.CharField(help_text='SHA-256 fingerprint of the public key.', max_length=64, unique=True, verbose_name='Fingerprint'),
        ),
        migrations.AlterField(
            model_name='systemkey',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='systemkey',
            name='name',
            field=models.CharField(default='default', max_length=100, unique=True, verbose_name='Key Name'),
        ),
        migrations.AlterField(
            model_name='systemkey',
            name='private_key',
            field=models.TextField(help_text='Private key', verbose_name='Private Key'),
        ),
        migrations.AlterField(
            model_name='systemkey',
            name='public_key',
            field=models.TextField(help_text='Public key (shared with partners).', verbose_name='Public Key'),
        ),
    ]
