# Generated by Django 5.2.5 on 2025-08-24 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_branches', to=settings.AUTH_USER_MODEL, verbose_name='Principal'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='school.branch', verbose_name='Branch'),
        ),
        migrations.AddField(
            model_name='branch',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='school.school', verbose_name='School'),
        ),
        migrations.AlterUniqueTogether(
            name='classroom',
            unique_together={('branch', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='branch',
            unique_together={('school', 'name')},
        ),
    ]
