# Generated by Django 5.2.5 on 2025-11-20 16:51

import audit.mixins
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Unique identifier')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Date modified')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('synced', models.BooleanField(default=False, help_text='Indicates whether this record has been synchronized with the replica system.', verbose_name='Synced')),
                ('purpose', models.CharField(choices=[('phone_verification', 'Phone Verification'), ('email_verification', 'Email Verification'), ('2fa', 'Two-Factor Authentication'), ('password_reset', 'Password Reset')], max_length=32, verbose_name='Purpose')),
                ('code', models.CharField(help_text='Hashed OTP code', max_length=255, verbose_name='Code')),
                ('delivery_method', models.CharField(choices=[('sms', 'SMS'), ('email', 'Email')], max_length=10, verbose_name='Delivery Method')),
                ('contact', models.CharField(help_text='Phone number or email address', max_length=255, verbose_name='Contact')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expires At')),
                ('is_used', models.BooleanField(default=False, verbose_name='Is Used')),
                ('retry_count', models.IntegerField(default=0, verbose_name='Retry Count')),
                ('identity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='otps', to='authentication.identity', verbose_name='Identity')),
            ],
            options={
                'verbose_name': 'OTP',
                'verbose_name_plural': 'OTPs',
                'ordering': ('-date_created',),
            },
            bases=(audit.mixins.AuditableMixin, models.Model),
        ),
    ]
