# Generated by Django 5.2.5 on 2025-09-10 08:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_identity_options_alter_loginlog_options_and_more'),
        ('otps', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otp',
            options={'ordering': ('-date_created',), 'verbose_name': 'OTP', 'verbose_name_plural': 'OTPs'},
        ),
        migrations.AlterField(
            model_name='otp',
            name='code',
            field=models.CharField(help_text='Hashed OTP code', max_length=255, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='otp',
            name='contact',
            field=models.CharField(help_text='Phone number or email address', max_length=255, verbose_name='Contact'),
        ),
        migrations.AlterField(
            model_name='otp',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date created'),
        ),
        migrations.AlterField(
            model_name='otp',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Date modified'),
        ),
        migrations.AlterField(
            model_name='otp',
            name='delivery_method',
            field=models.CharField(choices=[('SMS', 'SMS'), ('EMAIL', 'Email')], max_length=10, verbose_name='Delivery Method'),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expires At'),
        ),
        migrations.AlterField(
            model_name='otp',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Unique identifier'),
        ),
        migrations.AlterField(
            model_name='otp',
            name='identity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='otps', to='authentication.identity', verbose_name='Identity'),
        ),
        migrations.AlterField(
            model_name='otp',
            name='is_used',
            field=models.BooleanField(default=False, verbose_name='Is Used'),
        ),
        migrations.AlterField(
            model_name='otp',
            name='purpose',
            field=models.CharField(choices=[('PHONE_VERIFICATION', 'Phone Verification'), ('EMAIL_VERIFICATION', 'Email Verification'), ('2FA', 'Two-Factor Authentication'), ('PASSWORD_RESET', 'Password Reset')], max_length=32, verbose_name='Purpose'),
        ),
        migrations.AlterField(
            model_name='otp',
            name='retry_count',
            field=models.IntegerField(default=0, verbose_name='Retry Count'),
        ),
        migrations.AlterField(
            model_name='otp',
            name='synced',
            field=models.BooleanField(default=False, help_text='Indicates whether this record has been synchronized with the replica system.', verbose_name='Synced'),
        ),
        migrations.AlterField(
            model_name='otp',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
