# Generated by Django 5.2.5 on 2025-11-20 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otps', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otp',
            options={'ordering': ('-created_at',), 'verbose_name': 'OTP', 'verbose_name_plural': 'OTPs'},
        ),
        migrations.RenameField(
            model_name='otp',
            old_name='date_created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='otp',
            old_name='date_modified',
            new_name='updated_at',
        ),
    ]
