# Generated by Django 5.2.5 on 2025-12-06 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otps', '0003_alter_otp_options_rename_date_created_otp_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='contact',
        ),
    ]
