# Generated by Django 5.2.5 on 2025-12-06 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otps', '0004_remove_otp_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='contact',
            field=models.CharField(blank=True, help_text='Phone number or email address', max_length=255, null=True, verbose_name='Contact'),
        ),
    ]
