# Generated by Django 5.2.5 on 2025-12-11 20:45

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_delete_loginlog'),
        ('otps', '0005_otp_contact'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='contact',
            field=models.CharField(blank=True, help_text='Phone number in E.164 format or email address', max_length=255, null=True, verbose_name='Contact'),
        ),
        migrations.AlterField(
            model_name='otp',
            name='delivery_method',
            field=models.CharField(choices=[('SMS', 'SMS'), ('EMAIL', 'Email')], max_length=10, verbose_name='Delivery Method'),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 11, 20, 45, 16, 993637, tzinfo=datetime.timezone.utc), help_text='OTP becomes invalid after this time', verbose_name='Expires At'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='otp',
            name='purpose',
            field=models.CharField(choices=[('PHONE_VERIFICATION', 'Phone Verification'), ('EMAIL_VERIFICATION', 'Email Verification'), ('TWO_FACTOR_AUTHENTICATION', 'Two-Factor Authentication'), ('PASSWORD_RESET', 'Password Reset')], max_length=32, verbose_name='Purpose'),
        ),
        migrations.AlterField(
            model_name='otp',
            name='retry_count',
            field=models.PositiveSmallIntegerField(default=0, help_text='Number of failed validation attempts', verbose_name='Retry Count'),
        ),
        migrations.AlterField(
            model_name='otp',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='otps', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddIndex(
            model_name='otp',
            index=models.Index(fields=['user', 'purpose', 'is_used', 'expires_at'], name='otps_otp_user_id_991fe4_idx'),
        ),
        migrations.AddIndex(
            model_name='otp',
            index=models.Index(fields=['identity', 'purpose'], name='otps_otp_identit_96b439_idx'),
        ),
        migrations.AddIndex(
            model_name='otp',
            index=models.Index(fields=['contact', 'purpose', '-created_at'], name='otps_otp_contact_c72c9b_idx'),
        ),
        migrations.AddIndex(
            model_name='otp',
            index=models.Index(fields=['expires_at'], name='otps_otp_expires_d792a0_idx'),
        ),
        migrations.AddIndex(
            model_name='otp',
            index=models.Index(fields=['is_used', 'created_at'], name='otps_otp_is_used_fe4ce2_idx'),
        ),
        migrations.AddIndex(
            model_name='otp',
            index=models.Index(fields=['purpose', 'delivery_method'], name='otps_otp_purpose_8ccff1_idx'),
        ),
        migrations.AddConstraint(
            model_name='otp',
            constraint=models.CheckConstraint(condition=models.Q(('user__isnull', False), ('identity__isnull', False), _connector='OR'), name='otp_must_have_user_or_identity'),
        ),
    ]
