# Generated by Django 5.2.5 on 2025-11-20 16:51

import audit.mixins
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Unique identifier')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Date modified')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('synced', models.BooleanField(default=False, help_text='Indicates whether this record has been synchronized with the replica system.', verbose_name='Synced')),
                ('token', models.CharField(max_length=200, unique=True, verbose_name='Token')),
                ('expires_at', models.DateTimeField(verbose_name='Expiration Time')),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Source IP')),
                ('status', models.CharField(choices=[('ACTIVATION_PENDING', 'Activation Pending'), ('ACTIVE', 'Active'), ('EXPIRED', 'Expired')], default='ACTIVATION_PENDING', max_length=20, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Identity',
                'verbose_name_plural': 'Identities',
                'ordering': ('-date_created',),
            },
            bases=(audit.mixins.AuditableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='LoginLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Unique identifier')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Date modified')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('synced', models.BooleanField(default=False, help_text='Indicates whether this record has been synchronized with the replica system.', verbose_name='Synced')),
            ],
            options={
                'verbose_name': 'Login Log',
                'verbose_name_plural': 'Login Logs',
                'ordering': ('-date_created',),
            },
            bases=(audit.mixins.AuditableMixin, models.Model),
        ),
    ]
