# Generated by Django 5.2.5 on 2025-11-20 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='identity',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.device', verbose_name='Device'),
        ),
        migrations.AddField(
            model_name='identity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='loginlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddIndex(
            model_name='identity',
            index=models.Index(fields=['token'], name='authenticat_token_04f9aa_idx'),
        ),
        migrations.AddIndex(
            model_name='identity',
            index=models.Index(fields=['token', 'status'], name='authenticat_token_1485ad_idx'),
        ),
        migrations.AddIndex(
            model_name='identity',
            index=models.Index(fields=['user', 'device', 'status'], name='authenticat_user_id_4521c8_idx'),
        ),
    ]
