# Generated by Django 5.2.5 on 2025-11-20 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='identity',
            options={'ordering': ('-created_at',), 'verbose_name': 'Identity', 'verbose_name_plural': 'Identities'},
        ),
        migrations.AlterModelOptions(
            name='loginlog',
            options={'ordering': ('-created_at',), 'verbose_name': 'Login Log', 'verbose_name_plural': 'Login Logs'},
        ),
        migrations.RenameField(
            model_name='identity',
            old_name='date_created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='identity',
            old_name='date_modified',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='loginlog',
            old_name='date_created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='loginlog',
            old_name='date_modified',
            new_name='updated_at',
        ),
    ]
