# Generated by Django 5.2.5 on 2025-09-10 08:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_identity_device'),
        ('users', '0003_device'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='identity',
            options={'ordering': ('-date_created',), 'verbose_name': 'Identity', 'verbose_name_plural': 'Identities'},
        ),
        migrations.AlterModelOptions(
            name='loginlog',
            options={'ordering': ('-date_created',), 'verbose_name': 'Login Log', 'verbose_name_plural': 'Login Logs'},
        ),
        migrations.AlterField(
            model_name='identity',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date created'),
        ),
        migrations.AlterField(
            model_name='identity',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Date modified'),
        ),
        migrations.AlterField(
            model_name='identity',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.device', verbose_name='Device'),
        ),
        migrations.AlterField(
            model_name='identity',
            name='expires_at',
            field=models.DateTimeField(verbose_name='Expiration Time'),
        ),
        migrations.AlterField(
            model_name='identity',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Unique identifier'),
        ),
        migrations.AlterField(
            model_name='identity',
            name='source_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Source IP'),
        ),
        migrations.AlterField(
            model_name='identity',
            name='status',
            field=models.CharField(choices=[('ACTIVATION_PENDING', 'Activation Pending'), ('ACTIVE', 'Active'), ('EXPIRED', 'Expired')], default='ACTIVATION_PENDING', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='identity',
            name='synced',
            field=models.BooleanField(default=False, help_text='Indicates whether this record has been synchronized with the replica system.', verbose_name='Synced'),
        ),
        migrations.AlterField(
            model_name='identity',
            name='token',
            field=models.CharField(max_length=200, unique=True, verbose_name='Token'),
        ),
        migrations.AlterField(
            model_name='identity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='loginlog',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date created'),
        ),
        migrations.AlterField(
            model_name='loginlog',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Date modified'),
        ),
        migrations.AlterField(
            model_name='loginlog',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Unique identifier'),
        ),
        migrations.AlterField(
            model_name='loginlog',
            name='synced',
            field=models.BooleanField(default=False, help_text='Indicates whether this record has been synchronized with the replica system.', verbose_name='Synced'),
        ),
        migrations.AlterField(
            model_name='loginlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
