# Generated by Django 5.2.5 on 2025-12-11 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_identity_options_alter_loginlog_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoginLog',
        ),
    ]
