# Generated by Django 5.2.5 on 2025-11-20 16:51

import audit.mixins
import django.core.serializers.json
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Unique identifier')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Date modified')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('synced', models.BooleanField(default=False, help_text='Indicates whether this record has been synchronized with the replica system.', verbose_name='Synced')),
                ('request_id', models.UUIDField(editable=False, verbose_name='Request ID')),
                ('token', models.CharField(blank=True, max_length=255, null=True, verbose_name='Token')),
                ('is_authenticated', models.BooleanField(default=False, verbose_name='Is Authenticated')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('session_key', models.CharField(blank=True, max_length=40, null=True, verbose_name='Session Key')),
                ('request_method', models.CharField(max_length=10, verbose_name='Request Method')),
                ('request_path', models.TextField(verbose_name='Request Path')),
                ('request_data', models.JSONField(blank=True, null=True, verbose_name='Request Data')),
                ('is_secure', models.BooleanField(default=False, verbose_name='Is Secure')),
                ('view_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='View Name')),
                ('view_args', models.JSONField(blank=True, null=True, verbose_name='View Args')),
                ('view_kwargs', models.JSONField(blank=True, null=True, verbose_name='View Kwargs')),
                ('activity_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Activity Name')),
                ('exception_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Exception Type')),
                ('exception_message', models.TextField(blank=True, null=True, verbose_name='Exception Message')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Started At')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Ended At')),
                ('time_taken', models.FloatField(blank=True, null=True, verbose_name='Time Taken (s)')),
                ('response_status', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Response Status')),
                ('response_data', models.JSONField(blank=True, null=True, verbose_name='Response Data')),
            ],
            options={
                'verbose_name': 'Request Log',
                'verbose_name_plural': 'Request Logs',
                'ordering': ['-started_at'],
            },
            bases=(audit.mixins.AuditableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AuditConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Unique identifier')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Date modified')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('synced', models.BooleanField(default=False, help_text='Indicates whether this record has been synchronized with the replica system.', verbose_name='Synced')),
                ('model_name', models.CharField(max_length=100, unique=True, verbose_name='Model Name')),
                ('app_label', models.CharField(max_length=100, verbose_name='App Label')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Is Enabled')),
                ('track_create', models.BooleanField(default=True, verbose_name='Track Create')),
                ('track_update', models.BooleanField(default=True, verbose_name='Track Update')),
                ('track_delete', models.BooleanField(default=True, verbose_name='Track Delete')),
                ('excluded_fields', models.JSONField(blank=True, default=list, verbose_name='Excluded Fields')),
                ('retention_days', models.PositiveIntegerField(default=2555, verbose_name='Retention Days')),
            ],
            options={
                'verbose_name': 'Audit Configuration',
                'verbose_name_plural': 'Audit Configurations',
                'ordering': ['app_label', 'model_name'],
                'unique_together': {('app_label', 'model_name')},
            },
            bases=(audit.mixins.AuditableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Unique identifier')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Date modified')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('synced', models.BooleanField(default=False, help_text='Indicates whether this record has been synchronized with the replica system.', verbose_name='Synced')),
                ('request_id', models.UUIDField(blank=True, null=True, verbose_name='Request ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('request_method', models.CharField(blank=True, max_length=10, null=True, verbose_name='Request Method')),
                ('request_path', models.TextField(blank=True, null=True, verbose_name='Request Path')),
                ('activity_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Activity Name')),
                ('event_type', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('view', 'View'), ('login', 'Login'), ('logout', 'Logout'), ('permission_change', 'Permission Change'), ('data_export', 'Data Export'), ('bulk_operation', 'Bulk Operation'), ('system_event', 'System Event'), ('security_event', 'Security Event')], db_index=True, max_length=50, verbose_name='Event Type')),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='low', max_length=20, verbose_name='Severity')),
                ('object_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Object ID')),
                ('object_repr', models.CharField(blank=True, max_length=255, null=True, verbose_name='Object Representation')),
                ('changes', models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='Changes')),
                ('metadata', models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='Metadata')),
                ('api_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.apiclient', verbose_name='API Client')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='Content Type')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-date_created'],
            },
            bases=(audit.mixins.AuditableMixin, models.Model),
        ),
    ]
