# Generated by Django 5.2.5 on 2025-11-20 21:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_apiclientkey_options_and_more'),
        ('audit', '0002_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Audit Log', 'verbose_name_plural': 'Audit Logs'},
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='audit_audit_date_cr_2e991f_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='audit_audit_severit_3d99c2_idx',
        ),
        migrations.RenameField(
            model_name='auditconfiguration',
            old_name='date_created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='auditconfiguration',
            old_name='date_modified',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='auditlog',
            old_name='date_created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='auditlog',
            old_name='date_modified',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='requestlog',
            old_name='date_created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='requestlog',
            old_name='date_modified',
            new_name='updated_at',
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['created_at', 'event_type'], name='audit_audit_created_38ffa0_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['severity', 'created_at'], name='audit_audit_severit_effc12_idx'),
        ),
    ]
