# Generated by Django 5.2.5 on 2025-12-11 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_alter_auditlog_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='event_type',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('VIEW', 'View'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('PERMISSION_CHANGE', 'Permission Change'), ('DATA_EXPORT', 'Data Export'), ('BULK_OPERATION', 'Bulk Operation'), ('SYSTEM_EVENT', 'System Event'), ('SECURITY_EVENT', 'Security Event')], db_index=True, max_length=50, verbose_name='Event Type'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='severity',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], db_index=True, default='LOW', max_length=20, verbose_name='Severity'),
        ),
    ]
