# Generated by Django 5.2.5 on 2025-12-15 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0004_alter_auditlog_event_type_alter_auditlog_severity'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestlog',
            name='exception_traceback',
            field=models.TextField(blank=True, null=True, verbose_name='Exception Traceback'),
        ),
    ]
