# Generated by Django 5.2.5 on 2025-11-20 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'ordering': ('name', '-created_at'), 'verbose_name': 'Branch', 'verbose_name_plural': 'Branches'},
        ),
        migrations.AlterModelOptions(
            name='classroom',
            options={'ordering': ('name', '-created_at'), 'verbose_name': 'Classroom', 'verbose_name_plural': 'Classrooms'},
        ),
        migrations.RenameField(
            model_name='branch',
            old_name='date_created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='branch',
            old_name='date_modified',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='classroom',
            old_name='date_created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='classroom',
            old_name='date_modified',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='date_created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='date_modified',
            new_name='updated_at',
        ),
    ]
