# Generated by Django 5.2.5 on 2025-11-20 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_alter_branch_options_alter_classroom_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='grade_level',
            field=models.CharField(choices=[('baby_class', 'Baby Class'), ('pp_1', 'PP 1'), ('pp_2', 'PP 2'), ('grade_1', 'Grade 1'), ('grade_2', 'Grade 2'), ('grade_3', 'Grade 3'), ('grade_4', 'Grade 4'), ('grade_5', 'Grade 5'), ('grade_6', 'Grade 6'), ('grade_7', 'Grade 7'), ('grade_8', 'Grade 8'), ('grade_9', 'Grade 9')], default='', max_length=10, verbose_name='Grade Level'),
            preserve_default=False,
        ),
    ]
