# Generated by Django 5.2.5 on 2025-12-11 20:45

import audit.mixins
import base.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Unique identifier')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date modified')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('synced', models.BooleanField(default=False, help_text='Indicates whether this record has been synchronized with the replica system.', verbose_name='Synced')),
                ('system_name', models.CharField(default='Zanaka', help_text='The name of the system/application.', max_length=100, verbose_name='System Name')),
                ('cookie_secure', models.BooleanField(default=False, help_text='Whether auth cookies should be sent over HTTPS only.', verbose_name='Secure Cookies')),
                ('auth_token_cookie_name', models.CharField(default='auth_token', help_text='Name of the cookie used to store authentication token.', max_length=50, verbose_name='Auth Token Cookie Name')),
                ('auth_token_validity_seconds', models.IntegerField(default=300, help_text='Duration in seconds before an auth token expires.', verbose_name='Auth Token Validity (Seconds)')),
                ('auth_token_allow_header_fallback', models.BooleanField(default=True, help_text='Allow authentication token to be passed in headers as a fallback.', verbose_name='Allow Header Fallback')),
                ('two_factor_authentication_required', models.BooleanField(default=True, help_text='Require 2FA for user logins.', verbose_name='Require Two-Factor Authentication')),
                ('otp_length', models.IntegerField(default=4, help_text='Number of digits in generated OTPs.', verbose_name='OTP Length')),
                ('otp_validity_seconds', models.IntegerField(default=300, help_text='Time in seconds before OTP expires.', verbose_name='OTP Validity (Seconds)')),
                ('action_otp_validity_seconds', models.IntegerField(default=300, help_text='Time in seconds before OTP for specific actions expires.', verbose_name='Action OTP Validity (Seconds)')),
                ('max_otp_attempts', models.IntegerField(default=5, help_text='Maximum number of allowed OTP verification attempts.', verbose_name='Max OTP Attempts')),
                ('encrypted_header', models.CharField(default='X-Encrypted', help_text='Header name used to indicate encrypted requests.', max_length=50, verbose_name='Encrypted Header')),
                ('api_key_header', models.CharField(default='X-Api-Key', help_text='Header name used for API key authentication.', max_length=50, verbose_name='API Key Header')),
                ('api_key_verification_required', models.BooleanField(default=False, help_text='Require incoming API requests to include a valid API key.', verbose_name='API Key Verification Required')),
                ('api_key_verification_exempt_paths', models.JSONField(default=base.models.default_api_key_exempt_paths, help_text='List of URL paths exempted from API key validation.', verbose_name='API Key Validation Exempt Paths')),
                ('signature_verification_required', models.BooleanField(default=False, help_text='Require incoming API requests to include a valid cryptographic signature.', verbose_name='Signature Verification Required')),
                ('csrf_exempt_paths', models.JSONField(default=base.models.default_csrf_exempt_paths, help_text='List of URL paths that bypass CSRF validation.', verbose_name='CSRF Exempt Paths')),
                ('save_request_log_exempt_paths', models.JSONField(default=base.models.default_save_request_log_exempt_paths, help_text='List of URL paths exempted from request logging.', verbose_name='Save Request Log Exempt Paths')),
                ('send_notifications_async', models.BooleanField(default=False, help_text='Send notifications asynchronously if True.', verbose_name='Send Notifications Asynchronously')),
            ],
            options={
                'verbose_name': 'System Setting',
                'verbose_name_plural': 'System Settings',
            },
            bases=(audit.mixins.AuditableMixin, models.Model),
        ),
    ]
