# Generated by Django 5.2.5 on 2025-11-20 22:27

import audit.mixins
import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Unique identifier')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date modified')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('synced', models.BooleanField(default=False, help_text='Indicates whether this record has been synchronized with the replica system.', verbose_name='Synced')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.CharField(blank=True, max_length=100, verbose_name='Description')),
                ('default_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Default Amount')),
                ('category', models.CharField(choices=[('tuition', 'Tuition Fees'), ('transport', 'Transport Fees'), ('activity', 'Activity Fees'), ('uniform', 'Uniform'), ('other', 'Other')], default='other', max_length=50, verbose_name='Category')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'ordering': ['category', 'name'],
            },
            bases=(audit.mixins.AuditableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='BalanceSheet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Unique identifier')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date modified')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('synced', models.BooleanField(default=False, help_text='Indicates whether this record has been synchronized with the replica system.', verbose_name='Synced')),
                ('date', models.DateField(db_index=True, unique=True, verbose_name='Date')),
                ('total_invoiced', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Invoiced')),
                ('total_collected', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Collected')),
                ('total_outstanding', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Outstanding')),
                ('total_overdue', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Overdue')),
                ('mpesa_collections', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='M-Pesa Collections')),
                ('bank_collections', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Bank Collections')),
                ('cash_collections', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Cash Collections')),
                ('number_of_invoices', models.IntegerField(default=0, verbose_name='Number of Invoices')),
                ('number_of_payments', models.IntegerField(default=0, verbose_name='Number of Payments')),
                ('number_of_paid_invoices', models.IntegerField(default=0, verbose_name='Number of Paid Invoices')),
                ('number_of_pending_invoices', models.IntegerField(default=0, verbose_name='Number of Pending Invoices')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Generated By')),
            ],
            options={
                'ordering': ['-date'],
            },
            bases=(audit.mixins.AuditableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Unique identifier')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date modified')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('synced', models.BooleanField(default=False, help_text='Indicates whether this record has been synchronized with the replica system.', verbose_name='Synced')),
                ('invoice_number', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Invoice Number')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20, verbose_name='Status')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Total Amount')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Paid Amount')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Balance')),
                ('priority', models.IntegerField(default=1, help_text='Lower number = higher priority (1 is highest)', verbose_name='Priority')),
                ('due_date', models.DateField(verbose_name='Due Date')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('is_auto_generated', models.BooleanField(default=False, verbose_name='Is Auto Generated')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_invoices', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Student')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_invoices', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'ordering': ['priority', '-created_at'],
            },
            bases=(audit.mixins.AuditableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Unique identifier')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date modified')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('synced', models.BooleanField(default=False, help_text='Indicates whether this record has been synchronized with the replica system.', verbose_name='Synced')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.CharField(blank=True, max_length=100, verbose_name='Description')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Unit Price')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Amount')),
                ('fee_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finances.feeitem', verbose_name='Fee Item')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='finances.invoice', verbose_name='Invoice')),
            ],
            options={
                'ordering': ['id'],
            },
            bases=(audit.mixins.AuditableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Unique identifier')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date modified')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('synced', models.BooleanField(default=False, help_text='Indicates whether this record has been synchronized with the replica system.', verbose_name='Synced')),
                ('payment_reference', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Payment Reference')),
                ('payment_method', models.CharField(choices=[('mpesa', 'M-Pesa'), ('bank', 'Bank Transfer'), ('cash', 'Cash'), ('cheque', 'Cheque'), ('card', 'Card')], max_length=20, verbose_name='Payment Method')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Amount')),
                ('utilized_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Utilized Amount')),
                ('mpesa_receipt_number', models.CharField(blank=True, max_length=100, verbose_name='M-Pesa Receipt Number')),
                ('mpesa_phone_number', models.CharField(blank=True, max_length=15, verbose_name='M-Pesa Phone Number')),
                ('mpesa_transaction_date', models.DateTimeField(blank=True, null=True, verbose_name='M-Pesa Transaction Date')),
                ('bank_reference', models.CharField(blank=True, max_length=100, verbose_name='Bank Reference')),
                ('bank_name', models.CharField(blank=True, max_length=100, verbose_name='Bank Name')),
                ('transaction_id', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Transaction ID')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Verified At')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('reversed', 'Reversed')], db_index=True, default='pending', max_length=20, verbose_name='Status')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='verified_payments', to=settings.AUTH_USER_MODEL, verbose_name='Verified By')),
            ],
            options={
                'ordering': ['-created_at'],
            },
            bases=(audit.mixins.AuditableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MpesaTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Unique identifier')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date modified')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('synced', models.BooleanField(default=False, help_text='Indicates whether this record has been synchronized with the replica system.', verbose_name='Synced')),
                ('transaction_type', models.CharField(max_length=50, verbose_name='Transaction Type')),
                ('trans_id', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Transaction ID')),
                ('trans_time', models.CharField(max_length=50, verbose_name='Transaction Time')),
                ('trans_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Transaction Amount')),
                ('business_short_code', models.CharField(max_length=20, verbose_name='Business Short Code')),
                ('bill_ref_number', models.CharField(db_index=True, max_length=50, verbose_name='Bill Reference Number')),
                ('invoice_number', models.CharField(blank=True, max_length=50, verbose_name='Invoice Number')),
                ('msisdn', models.CharField(max_length=15, verbose_name='Phone Number')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='Middle Name')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='Last Name')),
                ('is_reconciled', models.BooleanField(default=False, verbose_name='Is Reconciled')),
                ('reconciliation_notes', models.TextField(blank=True, verbose_name='Reconciliation Notes')),
                ('raw_data', models.JSONField(verbose_name='Raw Data')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reconciled', 'Reconciled'), ('failed', 'Failed'), ('duplicate', 'Duplicate')], db_index=True, default='pending', max_length=20, verbose_name='Status')),
                ('payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mpesa_transaction', to='finances.payment', verbose_name='Payment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
            bases=(audit.mixins.AuditableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PaymentAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Unique identifier')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date modified')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('synced', models.BooleanField(default=False, help_text='Indicates whether this record has been synchronized with the replica system.', verbose_name='Synced')),
                ('allocated_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Allocated Amount')),
                ('allocation_order', models.PositiveIntegerField(verbose_name='Allocation Order')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_allocations', to='finances.invoice', verbose_name='Invoice')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='finances.payment', verbose_name='Payment')),
            ],
            options={
                'ordering': ['allocation_order'],
            },
            bases=(audit.mixins.AuditableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='GradeLevelFee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Unique identifier')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date modified')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('synced', models.BooleanField(default=False, help_text='Indicates whether this record has been synchronized with the replica system.', verbose_name='Synced')),
                ('grade_level', models.CharField(choices=[('baby_class', 'Baby Class'), ('pp_1', 'PP 1'), ('pp_2', 'PP 2'), ('grade_1', 'Grade 1'), ('grade_2', 'Grade 2'), ('grade_3', 'Grade 3'), ('grade_4', 'Grade 4'), ('grade_5', 'Grade 5'), ('grade_6', 'Grade 6'), ('grade_7', 'Grade 7'), ('grade_8', 'Grade 8'), ('grade_9', 'Grade 9')], max_length=10, verbose_name='Grade Level')),
                ('term', models.CharField(choices=[('term_1', 'Term 1'), ('term_2', 'Term 2'), ('term_3', 'Term 3')], max_length=20, verbose_name='Term')),
                ('academic_year', models.CharField(max_length=9, verbose_name='Academic Year')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Amount')),
                ('is_mandatory', models.BooleanField(default=True, verbose_name='Is Mandatory')),
                ('fee_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finances.feeitem', verbose_name='Fee Item')),
            ],
            options={
                'ordering': ['grade_level', 'term'],
                'unique_together': {('fee_item', 'grade_level', 'term', 'academic_year')},
            },
            bases=(audit.mixins.AuditableMixin, models.Model),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['student', 'status'], name='finances_in_student_be99a8_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['due_date', 'status'], name='finances_in_due_dat_414e2a_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['priority', 'status'], name='finances_in_priorit_ad20bf_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_method', 'status'], name='finances_pa_payment_17ad04_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['mpesa_receipt_number'], name='finances_pa_mpesa_r_727914_idx'),
        ),
        migrations.AddIndex(
            model_name='mpesatransaction',
            index=models.Index(fields=['bill_ref_number', 'is_reconciled'], name='finances_mp_bill_re_ae57ce_idx'),
        ),
        migrations.AddIndex(
            model_name='mpesatransaction',
            index=models.Index(fields=['trans_id'], name='finances_mp_trans_i_495ede_idx'),
        ),
    ]
