# Generated by Django 5.2.5 on 2025-11-21 01:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='invoice_number',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='name',
        ),
        migrations.RemoveField(
            model_name='mpesatransaction',
            name='invoice_number',
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_reference',
            field=models.CharField(blank=True, db_index=True, max_length=50, unique=True, verbose_name='Invoice Reference'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AddField(
            model_name='payment',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentallocation',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_reference',
            field=models.CharField(blank=True, db_index=True, max_length=50, unique=True, verbose_name='Payment Reference'),
        ),
    ]
