# Generated by Django 5.2.5 on 2025-11-25 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_remove_invoice_invoice_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='paid_amount',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='utilized_amount',
        ),
    ]
