# Generated by Django 5.2.5 on 2025-12-03 08:15

import audit.mixins
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0003_remove_invoice_balance_remove_invoice_paid_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Unique identifier')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date modified')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('synced', models.BooleanField(default=False, help_text='Indicates whether this record has been synchronized with the replica system.', verbose_name='Synced')),
                ('description', models.CharField(blank=True, max_length=100, verbose_name='Description')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('contact_person', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('tax_id', models.CharField(blank=True, max_length=50, verbose_name='KRA PIN')),
                ('payment_terms', models.CharField(choices=[('pending', 'Immediate'), ('net_7', 'Net 7 Days'), ('net_15', 'Net 15 Days'), ('net_30', 'Net 30 Days'), ('net_60', 'Net 60 Days')], default='net_30', max_length=20)),
                ('mpesa_pochi_number', models.CharField(blank=True, help_text='Pochi la Biashara phone number', max_length=20)),
                ('mpesa_paybill_number', models.CharField(blank=True, help_text='Paybill business number', max_length=20)),
                ('mpesa_paybill_account', models.CharField(blank=True, help_text='Account number to use with Paybill', max_length=50)),
                ('mpesa_till_number', models.CharField(blank=True, help_text='Buy Goods Till number', max_length=20)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('bank_account', models.CharField(blank=True, max_length=50)),
                ('bank_branch', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
            bases=(audit.mixins.AuditableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Unique identifier')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date modified')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('synced', models.BooleanField(default=False, help_text='Indicates whether this record has been synchronized with the replica system.', verbose_name='Synced')),
                ('description', models.CharField(blank=True, max_length=100, verbose_name='Description')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('budget_allocated', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('head', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_departments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
            bases=(audit.mixins.AuditableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Unique identifier')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date modified')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('synced', models.BooleanField(default=False, help_text='Indicates whether this record has been synchronized with the replica system.', verbose_name='Synced')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.CharField(blank=True, max_length=100, verbose_name='Description')),
                ('expense_reference', models.CharField(db_index=True, max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('expense_date', models.DateField(default=django.utils.timezone.now)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('cheque', 'Cheque'), ('bank_transfer', 'Bank Transfer'), ('mpesa', 'M-Pesa'), ('card', 'Card'), ('petty_cash', 'Petty Cash')], max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20)),
                ('invoice_number', models.CharField(blank=True, max_length=100)),
                ('receipt_number', models.CharField(blank=True, max_length=100)),
                ('cheque_number', models.CharField(blank=True, max_length=50)),
                ('transaction_reference', models.CharField(blank=True, max_length=100)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('is_taxable', models.BooleanField(default=False)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurrence_frequency', models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annually', 'Annually')], max_length=20, null=True)),
                ('notes', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_expenses', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='finances.department')),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='paid_expenses', to=settings.AUTH_USER_MODEL)),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rejected_expenses', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_expenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-expense_date', '-created_at'],
            },
            bases=(audit.mixins.AuditableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ExpenseAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Unique identifier')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date modified')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('synced', models.BooleanField(default=False, help_text='Indicates whether this record has been synchronized with the replica system.', verbose_name='Synced')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.CharField(blank=True, max_length=100, verbose_name='Description')),
                ('file', models.FileField(upload_to='expenses/attachments/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'doc', 'docx', 'xls', 'xlsx'])])),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=50)),
                ('file_size', models.IntegerField(help_text='Size in bytes')),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='finances.expense')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
            bases=(audit.mixins.AuditableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Unique identifier')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date modified')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('synced', models.BooleanField(default=False, help_text='Indicates whether this record has been synchronized with the replica system.', verbose_name='Synced')),
                ('description', models.CharField(blank=True, max_length=100, verbose_name='Description')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('has_budget', models.BooleanField(default=False)),
                ('monthly_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('annual_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('is_active', models.BooleanField(default=True)),
                ('requires_approval', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='finances.expensecategory')),
            ],
            options={
                'verbose_name_plural': 'Expense Categories',
                'ordering': ['name'],
            },
            bases=(audit.mixins.AuditableMixin, models.Model),
        ),
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='finances.expensecategory'),
        ),
        migrations.CreateModel(
            name='PettyCash',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Unique identifier')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date modified')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('synced', models.BooleanField(default=False, help_text='Indicates whether this record has been synchronized with the replica system.', verbose_name='Synced')),
                ('fund_name', models.CharField(max_length=100)),
                ('initial_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('current_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('closed', 'Closed')], default='active', max_length=20)),
                ('custodian', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='petty_cash_funds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Petty Cash Fund',
                'verbose_name_plural': 'Petty Cash Funds',
            },
            bases=(audit.mixins.AuditableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PettyCashTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Unique identifier')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date modified')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('synced', models.BooleanField(default=False, help_text='Indicates whether this record has been synchronized with the replica system.', verbose_name='Synced')),
                ('description', models.TextField()),
                ('transaction_type', models.CharField(choices=[('disbursement', 'Disbursement'), ('replenishment', 'Replenishment'), ('adjustment', 'Adjustment')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('balance_before', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('expense', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='petty_cash_transaction', to='finances.expense')),
                ('petty_cash_fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='finances.pettycash')),
                ('processed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
            bases=(audit.mixins.AuditableMixin, models.Model),
        ),
        migrations.AddField(
            model_name='expense',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='finances.vendor'),
        ),
        migrations.CreateModel(
            name='ExpenseBudget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Unique identifier')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date modified')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('synced', models.BooleanField(default=False, help_text='Indicates whether this record has been synchronized with the replica system.', verbose_name='Synced')),
                ('fiscal_year', models.CharField(max_length=9)),
                ('budget_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('period', models.CharField(choices=[('annual', 'Annual'), ('quarterly', 'Quarterly'), ('monthly', 'Monthly')], default='annual', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='finances.department')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='finances.expensecategory')),
            ],
            options={
                'ordering': ['-fiscal_year', 'category'],
                'unique_together': {('fiscal_year', 'category', 'department', 'period')},
            },
            bases=(audit.mixins.AuditableMixin, models.Model),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['expense_date', 'status'], name='finances_ex_expense_ec327d_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['category', 'status'], name='finances_ex_categor_26e598_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['department', 'status'], name='finances_ex_departm_036f3a_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['vendor'], name='finances_ex_vendor__0830ce_idx'),
        ),
    ]
