# Generated by Django 5.2.5 on 2025-12-11 20:45

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0004_vendor_department_expense_expenseattachment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='balancesheet',
            options={'ordering': ['-created_at'], 'verbose_name': 'Balance Sheet', 'verbose_name_plural': 'Balance Sheets'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['name'], 'verbose_name': 'Department', 'verbose_name_plural': 'Departments'},
        ),
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-expense_date', '-created_at'], 'verbose_name': 'Expense', 'verbose_name_plural': 'Expenses'},
        ),
        migrations.AlterModelOptions(
            name='expenseattachment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Expense Attachment', 'verbose_name_plural': 'Expense Attachments'},
        ),
        migrations.AlterModelOptions(
            name='expensebudget',
            options={'ordering': ['-fiscal_year', 'category'], 'verbose_name': 'Expense Budget', 'verbose_name_plural': 'Expense Budgets'},
        ),
        migrations.AlterModelOptions(
            name='expensecategory',
            options={'ordering': ['name'], 'verbose_name': 'Expense Category', 'verbose_name_plural': 'Expense Categories'},
        ),
        migrations.AlterModelOptions(
            name='feeitem',
            options={'ordering': ['category', 'name'], 'verbose_name': 'Fee Item', 'verbose_name_plural': 'Fee Items'},
        ),
        migrations.AlterModelOptions(
            name='gradelevelfee',
            options={'ordering': ['grade_level', 'term'], 'verbose_name': 'Grade Level Fee', 'verbose_name_plural': 'Grade Level Fees'},
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['priority', '-created_at'], 'verbose_name': 'Invoice', 'verbose_name_plural': 'Invoices'},
        ),
        migrations.AlterModelOptions(
            name='invoiceitem',
            options={'ordering': ['-created_at'], 'verbose_name': 'Invoice Item', 'verbose_name_plural': 'Invoice Items'},
        ),
        migrations.AlterModelOptions(
            name='mpesatransaction',
            options={'ordering': ['-created_at'], 'verbose_name': 'M-Pesa Transaction', 'verbose_name_plural': 'M-Pesa Transactions'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Payment', 'verbose_name_plural': 'Payments'},
        ),
        migrations.AlterModelOptions(
            name='paymentallocation',
            options={'ordering': ['created_at'], 'verbose_name': 'Payment Allocation', 'verbose_name_plural': 'Payment Allocations'},
        ),
        migrations.AlterModelOptions(
            name='pettycashtransaction',
            options={'ordering': ['-created_at'], 'verbose_name': 'Petty Cash Transaction', 'verbose_name_plural': 'Petty Cash Transactions'},
        ),
        migrations.AlterModelOptions(
            name='vendor',
            options={'ordering': ['name'], 'verbose_name': 'Vendor', 'verbose_name_plural': 'Vendors'},
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='tax_id',
            new_name='kra_pin',
        ),
        migrations.AlterField(
            model_name='department',
            name='budget_allocated',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Budget Allocated'),
        ),
        migrations.AlterField(
            model_name='department',
            name='head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_departments', to=settings.AUTH_USER_MODEL, verbose_name='Department Head'),
        ),
        migrations.AlterField(
            model_name='department',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Department Name'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Approved At'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_expenses', to=settings.AUTH_USER_MODEL, verbose_name='Approved By'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='finances.expensecategory', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='cheque_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Cheque Number'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='finances.department', verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Expense Date'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense_reference',
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Expense Reference'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Invoice Number'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='is_recurring',
            field=models.BooleanField(default=False, verbose_name='Is Recurring'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='is_taxable',
            field=models.BooleanField(default=False, verbose_name='Is Taxable'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Paid At'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='paid_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='paid_expenses', to=settings.AUTH_USER_MODEL, verbose_name='Paid By'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('CHEQUE', 'Cheque'), ('BANK_TRANSFER', 'Bank Transfer'), ('MPESA', 'M-Pesa'), ('CARD', 'Card'), ('PETTY_CASH', 'Petty Cash')], max_length=20, verbose_name='Payment Method'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Receipt Number'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='recurrence_frequency',
            field=models.CharField(blank=True, choices=[('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('ANNUALLY', 'Annually')], max_length=20, null=True, verbose_name='Recurrence Frequency'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Rejected At'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rejected_expenses', to=settings.AUTH_USER_MODEL, verbose_name='Rejected By'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='rejection_reason',
            field=models.TextField(blank=True, verbose_name='Rejection Reason'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_expenses', to=settings.AUTH_USER_MODEL, verbose_name='Requested By'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Tax Amount'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Tax Rate'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='transaction_reference',
            field=models.CharField(blank=True, max_length=100, verbose_name='Transaction Reference'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='finances.vendor', verbose_name='Vendor'),
        ),
        migrations.AlterField(
            model_name='expenseattachment',
            name='expense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='finances.expense', verbose_name='Expense'),
        ),
        migrations.AlterField(
            model_name='expenseattachment',
            name='file',
            field=models.FileField(upload_to='expenses/attachments/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'doc', 'docx', 'xls', 'xlsx'])], verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='expenseattachment',
            name='file_name',
            field=models.CharField(max_length=255, verbose_name='File Name'),
        ),
        migrations.AlterField(
            model_name='expenseattachment',
            name='file_size',
            field=models.IntegerField(help_text='Size in bytes', verbose_name='File Size'),
        ),
        migrations.AlterField(
            model_name='expenseattachment',
            name='file_type',
            field=models.CharField(max_length=50, verbose_name='File Type'),
        ),
        migrations.AlterField(
            model_name='expenseattachment',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Uploaded By'),
        ),
        migrations.AlterField(
            model_name='expensebudget',
            name='budget_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Budget Amount'),
        ),
        migrations.AlterField(
            model_name='expensebudget',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='finances.expensecategory', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='expensebudget',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='expensebudget',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='finances.department', verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='expensebudget',
            name='end_date',
            field=models.DateField(verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='expensebudget',
            name='fiscal_year',
            field=models.CharField(max_length=9, verbose_name='Fiscal Year'),
        ),
        migrations.AlterField(
            model_name='expensebudget',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='expensebudget',
            name='period',
            field=models.CharField(choices=[('ANNUAL', 'Annual'), ('QUARTERLY', 'Quarterly'), ('MONTHLY', 'Monthly')], default='ANNUAL', max_length=20, verbose_name='Budget Period'),
        ),
        migrations.AlterField(
            model_name='expensebudget',
            name='start_date',
            field=models.DateField(verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='expensecategory',
            name='annual_budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Annual Budget'),
        ),
        migrations.AlterField(
            model_name='expensecategory',
            name='has_budget',
            field=models.BooleanField(default=False, verbose_name='Has Budget'),
        ),
        migrations.AlterField(
            model_name='expensecategory',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='expensecategory',
            name='monthly_budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monthly Budget'),
        ),
        migrations.AlterField(
            model_name='expensecategory',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Category Name'),
        ),
        migrations.AlterField(
            model_name='expensecategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='finances.expensecategory', verbose_name='Parent Category'),
        ),
        migrations.AlterField(
            model_name='expensecategory',
            name='requires_approval',
            field=models.BooleanField(default=False, verbose_name='Requires Approval'),
        ),
        migrations.AlterField(
            model_name='feeitem',
            name='category',
            field=models.CharField(choices=[('TUITION', 'Tuition Fees'), ('TRANSPORT', 'Transport Fees'), ('ACTIVITY', 'Activity Fees'), ('UNIFORM', 'Uniform'), ('OTHER', 'Other')], default='OTHER', max_length=50, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='gradelevelfee',
            name='term',
            field=models.CharField(choices=[('TERM_1', 'Term 1'), ('TERM_2', 'Term 2'), ('TERM_3', 'Term 3')], max_length=20, verbose_name='Term'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('PARTIALLY_PAID', 'Partially Paid'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='mpesatransaction',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('RECONCILED', 'Reconciled'), ('FAILED', 'Failed'), ('DUPLICATE', 'Duplicate')], db_index=True, default='PENDING', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('MPESA', 'M-Pesa'), ('BANK', 'Bank Transfer'), ('CASH', 'Cash'), ('CHEQUE', 'Cheque'), ('CARD', 'Card')], max_length=20, verbose_name='Payment Method'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REVERSED', 'Reversed')], db_index=True, default='PENDING', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='pettycash',
            name='current_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Current Balance'),
        ),
        migrations.AlterField(
            model_name='pettycash',
            name='custodian',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='petty_cash_funds', to=settings.AUTH_USER_MODEL, verbose_name='Custodian'),
        ),
        migrations.AlterField(
            model_name='pettycash',
            name='fund_name',
            field=models.CharField(max_length=100, verbose_name='Fund Name'),
        ),
        migrations.AlterField(
            model_name='pettycash',
            name='initial_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Initial Amount'),
        ),
        migrations.AlterField(
            model_name='pettycash',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('CLOSED', 'Closed')], default='ACTIVE', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='pettycashtransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='pettycashtransaction',
            name='balance_after',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Balance After'),
        ),
        migrations.AlterField(
            model_name='pettycashtransaction',
            name='balance_before',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Balance Before'),
        ),
        migrations.AlterField(
            model_name='pettycashtransaction',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='pettycashtransaction',
            name='expense',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='petty_cash_transaction', to='finances.expense', verbose_name='Expense'),
        ),
        migrations.AlterField(
            model_name='pettycashtransaction',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='pettycashtransaction',
            name='petty_cash_fund',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='finances.pettycash', verbose_name='Petty Cash Fund'),
        ),
        migrations.AlterField(
            model_name='pettycashtransaction',
            name='processed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Processed By'),
        ),
        migrations.AlterField(
            model_name='pettycashtransaction',
            name='transaction_type',
            field=models.CharField(choices=[('DISBURSEMENT', 'Disbursement'), ('REPLENISHMENT', 'Replenishment'), ('ADJUSTMENT', 'Adjustment')], max_length=20, verbose_name='Transaction Type'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='address',
            field=models.TextField(blank=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='bank_account',
            field=models.CharField(blank=True, max_length=50, verbose_name='Bank Account Number'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='bank_branch',
            field=models.CharField(blank=True, max_length=100, verbose_name='Bank Branch'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Bank Name'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='contact_person',
            field=models.CharField(blank=True, max_length=100, verbose_name='Contact Person'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='mpesa_paybill_account',
            field=models.CharField(blank=True, help_text='Account number to use with Paybill', max_length=50, verbose_name='MPESA Paybill Account'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='mpesa_paybill_number',
            field=models.CharField(blank=True, help_text='Paybill business number', max_length=20, verbose_name='MPESA Paybill Number'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='mpesa_pochi_number',
            field=models.CharField(blank=True, help_text='Pochi la Biashara phone number', max_length=20, verbose_name='MPESA Pochi Number'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='mpesa_till_number',
            field=models.CharField(blank=True, help_text='Buy Goods Till number', max_length=20, verbose_name='MPESA Till Number'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Vendor Name'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='payment_terms',
            field=models.CharField(choices=[('IMMEDIATE', 'Immediate'), ('NET_7', 'Net 7 Days'), ('NET_15', 'Net 15 Days'), ('NET_30', 'Net 30 Days'), ('NET_60', 'Net 60 Days')], default='NET_30', max_length=20, verbose_name='Payment Terms'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Phone Number'),
        ),
    ]
