# Generated by Django 5.2.5 on 2025-12-25 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0005_alter_balancesheet_options_alter_department_options_and_more'),
        ('schools', '0004_classroom_grade_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feeitem',
            options={'ordering': ['school', 'category', 'name'], 'verbose_name': 'Fee Item', 'verbose_name_plural': 'Fee Items'},
        ),
        migrations.AddField(
            model_name='feeitem',
            name='branches',
            field=models.ManyToManyField(blank=True, help_text='Leave blank to apply to all branches in the school', related_name='fee_items', to='schools.branch', verbose_name='Branches'),
        ),
        migrations.AddField(
            model_name='feeitem',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fee_items', to='schools.school', verbose_name='School'),
        ),
        migrations.AlterUniqueTogether(
            name='feeitem',
            unique_together={('school', 'name')},
        ),
        migrations.AddIndex(
            model_name='feeitem',
            index=models.Index(fields=['school'], name='finances_fe_school__54f7f4_idx'),
        ),
        migrations.AddIndex(
            model_name='feeitem',
            index=models.Index(fields=['school', 'is_active'], name='finances_fe_school__3fc017_idx'),
        ),
    ]
