# Generated by Django 5.2.5 on 2025-12-25 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0006_alter_feeitem_options_feeitem_branches_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
    ]
