# Generated by Django 5.2.5 on 2025-12-25 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0007_alter_invoice_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='priority_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finances.invoice', verbose_name='Priority Invoice'),
        ),
    ]
