# Generated by Django 5.2.5 on 2025-12-27 09:31

import audit.mixins
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0008_payment_priority_invoice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Unique identifier')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date modified')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('synced', models.BooleanField(default=False, help_text='Indicates whether this record has been synchronized with the replica system.', verbose_name='Synced')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Refund Amount')),
                ('refund_method', models.CharField(choices=[('MPESA', 'M-Pesa'), ('BANK', 'Bank Transfer'), ('CASH', 'Cash'), ('CHEQUE', 'Cheque'), ('CARD', 'Card')], max_length=20, verbose_name='Refund Method')),
                ('mpesa_receipt_number', models.CharField(blank=True, max_length=100, verbose_name='M-Pesa Receipt Number')),
                ('mpesa_phone_number', models.CharField(blank=True, max_length=15, verbose_name='M-Pesa Phone Number')),
                ('mpesa_transaction_date', models.DateTimeField(blank=True, null=True, verbose_name='M-Pesa Transaction Date')),
                ('bank_reference', models.CharField(blank=True, max_length=100, verbose_name='Bank Reference')),
                ('bank_name', models.CharField(blank=True, max_length=100, verbose_name='Bank Name')),
                ('transaction_id', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Transaction ID')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='General Reference')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('processed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Processed At')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Refund',
                'verbose_name_plural': 'Refunds',
                'ordering': ['-processed_at', '-created_at'],
            },
            bases=(audit.mixins.AuditableMixin, models.Model),
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='finances_pa_mpesa_r_727914_idx',
        ),
        migrations.AddField(
            model_name='payment',
            name='reversal_reason',
            field=models.TextField(blank=True, verbose_name='Reversal Reason'),
        ),
        migrations.AddField(
            model_name='payment',
            name='reversed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Reversed At'),
        ),
        migrations.AddField(
            model_name='payment',
            name='reversed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversed_payments', to=settings.AUTH_USER_MODEL, verbose_name='Reversed By'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REVERSED', 'Reversed'), ('REFUNDED', 'Refunded'), ('PARTIALLY_REFUNDED', 'Partially Refunded')], db_index=True, default='PENDING', max_length=30, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='refund',
            name='original_payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='finances.payment', verbose_name='Original Payment'),
        ),
        migrations.AddField(
            model_name='refund',
            name='processed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Processed By'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['original_payment'], name='finances_re_origina_1c5fcb_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['refund_method', 'status'], name='finances_re_refund__75a383_idx'),
        ),
    ]
