# Generated by Django 5.2.5 on 2025-12-29 16:53

import audit.mixins
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0010_refund_cancellation_reason_refund_cancelled_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Unique identifier')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date modified')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('synced', models.BooleanField(default=False, help_text='Indicates whether this record has been synchronized with the replica system.', verbose_name='Synced')),
                ('bulk_reference', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Bulk Reference')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('student_count', models.PositiveIntegerField(verbose_name='Number of Students')),
                ('invoice_count', models.PositiveIntegerField(verbose_name='Number of Invoices Created')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Total Amount Invoiced')),
                ('due_date', models.DateField(verbose_name='Common Due Date')),
                ('priority', models.IntegerField(default=1, verbose_name='Priority')),
                ('is_auto_generated', models.BooleanField(default=True, verbose_name='Auto Generated')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bulk_invoices', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('invoices', models.ManyToManyField(related_name='bulk_invoices', to='finances.invoice', verbose_name='Invoices')),
            ],
            options={
                'verbose_name': 'Bulk Invoice',
                'verbose_name_plural': 'Bulk Invoices',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_by'], name='finances_bu_created_e693c1_idx'), models.Index(fields=['due_date'], name='finances_bu_due_dat_4ee588_idx'), models.Index(fields=['bulk_reference'], name='finances_bu_bulk_re_100e65_idx')],
            },
            bases=(audit.mixins.AuditableMixin, models.Model),
        ),
    ]
