# Generated by Django 5.2.5 on 2025-12-29 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0011_bulkinvoice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkinvoice',
            name='cancellation_reason',
            field=models.TextField(blank=True, verbose_name='Cancellation Reason'),
        ),
        migrations.AddField(
            model_name='bulkinvoice',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Cancelled At'),
        ),
        migrations.AddField(
            model_name='bulkinvoice',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cancelled_bulk_invoices', to=settings.AUTH_USER_MODEL, verbose_name='Cancelled By'),
        ),
        migrations.AddField(
            model_name='bulkinvoice',
            name='description',
            field=models.CharField(blank=True, help_text='A short description or title for this bulk invoice (e.g., "Term 1 2025 Fees", "Transport Fees Q4")', max_length=255, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='bulkinvoice',
            name='is_cancelled',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Is Cancelled'),
        ),
        migrations.AddIndex(
            model_name='bulkinvoice',
            index=models.Index(fields=['is_cancelled'], name='finances_bu_is_canc_7bfec2_idx'),
        ),
    ]
