# Generated by Django 5.2.5 on 2026-01-01 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0012_bulkinvoice_cancellation_reason_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='description',
        ),
    ]
