# Generated by Django 5.2.5 on 2026-01-01 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0013_remove_vendor_description'),
        ('schools', '0004_classroom_grade_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schools.school', verbose_name='School'),
        ),
    ]
