# Generated by Django 5.2.5 on 2026-01-01 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0014_vendor_school'),
        ('schools', '0004_classroom_grade_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='branches',
            field=models.ManyToManyField(blank=True, help_text='Leave blank for school-level expense (applies to all branches)', related_name='expenses', to='schools.branch', verbose_name='Branches'),
        ),
        migrations.AddField(
            model_name='expense',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='schools.school', verbose_name='School'),
        ),
    ]
