# Generated by Django 5.2.5 on 2026-01-01 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0015_expense_branches_expense_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenseattachment',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
    ]
