# Generated by Django 5.2.5 on 2026-01-01 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0016_expenseattachment_is_active'),
        ('schools', '0004_classroom_grade_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schools.school', verbose_name='School'),
        ),
    ]
