# Generated by Django 5.2.5 on 2026-01-01 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0018_alter_department_name'),
        ('schools', '0004_classroom_grade_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expensecategory',
            name='parent',
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schools.school', verbose_name='School'),
        ),
        migrations.AlterField(
            model_name='expensecategory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Category Name'),
        ),
    ]
