# Generated by Django 5.2.5 on 2026-01-02 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0019_remove_expensecategory_parent_expensecategory_school_and_more'),
        ('schools', '0004_classroom_grade_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='pettycash',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schools.school', verbose_name='School'),
        ),
    ]
