# Generated by Django 5.2.5 on 2025-11-20 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='notifications.provider'),
        ),
        migrations.AddField(
            model_name='notification',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='notifications.template'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'date_created'], name='notificatio_user_id_9d79a3_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['unique_key'], name='notificatio_unique__d3119b_idx'),
        ),
    ]
