# Generated by Django 5.2.5 on 2025-11-20 21:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='provider',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='template',
            options={'ordering': ('-created_at',)},
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='notificatio_user_id_9d79a3_idx',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='date_created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='date_modified',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='provider',
            old_name='date_created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='provider',
            old_name='date_modified',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='template',
            old_name='date_created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='template',
            old_name='date_modified',
            new_name='updated_at',
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'created_at'], name='notificatio_user_id_c62b26_idx'),
        ),
    ]
