# Generated by Django 5.2.5 on 2025-12-11 20:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_options_alter_provider_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ('-created_at',), 'verbose_name': 'Notification', 'verbose_name_plural': 'Notifications'},
        ),
        migrations.AlterModelOptions(
            name='provider',
            options={'ordering': ('priority', 'name'), 'verbose_name': 'Notification Provider', 'verbose_name_plural': 'Notification Providers'},
        ),
        migrations.AlterModelOptions(
            name='template',
            options={'ordering': ('-created_at',), 'verbose_name': 'Notification Template', 'verbose_name_plural': 'Notification Templates'},
        ),
        migrations.AlterField(
            model_name='notification',
            name='context',
            field=models.JSONField(default=dict, help_text='Variables to render in the template', verbose_name='Template Context'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='failure_message',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Failure Message'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='failure_traceback',
            field=models.TextField(blank=True, null=True, verbose_name='Failure Traceback'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='frequency',
            field=models.CharField(choices=[('ONCE', 'Once'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], default='ONCE', max_length=20, verbose_name='Frequency'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS')], max_length=10, verbose_name='Notification Type'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='notifications.provider', verbose_name='Provider'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='recipients',
            field=models.JSONField(default=list, help_text='List of emails or phone numbers', verbose_name='Recipients'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='sent_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Sent At'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('QUEUED', 'Queued'), ('CONFIRMATION_PENDING', 'Confirmation Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=30, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='notifications.template', verbose_name='Template'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='unique_key',
            field=models.CharField(blank=True, help_text='Prevents duplicate notifications', max_length=255, null=True, unique=True, verbose_name='Unique Key'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='class_name',
            field=models.CharField(help_text="Name of the provider's class", max_length=100, verbose_name='Callback Class'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='config',
            field=models.JSONField(default=dict, help_text='Provider-specific settings (API keys, endpoints, etc.)', verbose_name='Configuration'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='notification_type',
            field=models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS')], max_length=10, verbose_name='Notification Type'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='priority',
            field=models.IntegerField(blank=True, help_text='Lower number = higher priority', null=True, verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='template',
            name='body',
            field=models.TextField(verbose_name='Body'),
        ),
        migrations.AlterField(
            model_name='template',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='template',
            name='notification_type',
            field=models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS')], max_length=10, verbose_name='Notification Type'),
        ),
        migrations.AlterField(
            model_name='template',
            name='subject',
            field=models.CharField(blank=True, max_length=255, verbose_name='Subject'),
        ),
        migrations.AlterUniqueTogether(
            name='provider',
            unique_together={('notification_type', 'class_name')},
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['status', 'created_at'], name='notificatio_status_9a4505_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type', 'status'], name='notificatio_notific_a659f1_idx'),
        ),
    ]
