# Generated by Django 5.2.5 on 2025-09-10 08:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_template'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ('-date_created',), 'verbose_name': 'Notification', 'verbose_name_plural': 'Notifications'},
        ),
        migrations.AlterField(
            model_name='notification',
            name='context',
            field=models.JSONField(default=dict, verbose_name='Context'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date created'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Date modified'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='delivery_method',
            field=models.CharField(choices=[('SMS', 'SMS'), ('EMAIL', 'Email'), ('PUSH', 'Push')], default='PUSH', max_length=10, verbose_name='Delivery Method'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='frequency',
            field=models.CharField(choices=[('ONCE', 'Once'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], default='ONCE', max_length=20, verbose_name='Frequency'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Unique identifier'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='recipients',
            field=models.JSONField(default=list, help_text='List of recipients for the notification.', verbose_name='Recipients'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='response_data',
            field=models.JSONField(blank=True, null=True, verbose_name='Response Data'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='sent_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Sent Time'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('QUEUED', 'Queued'), ('CONFIRMATION_PENDING', 'Confirmation Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='PENDING', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='synced',
            field=models.BooleanField(default=False, help_text='Indicates whether this record has been synchronized with the replica system.', verbose_name='Synced'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='template',
            field=models.CharField(max_length=100, verbose_name='Template'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='unique_key',
            field=models.CharField(blank=True, help_text='Unique key to identify the notification. Generated when saving the notification.', max_length=255, null=True, unique=True, verbose_name='Unique Key'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
